### ISSUE TITLE
No scraps files

### ISSUE THREAD

**Issue by justincbagley** [ISUgenomics/SequelTools#14]
Hi, The sequencing service we used for PacBio SMRT Sequel II sequencing of a plant species only returned subreads to us. I have no scraps files. Can I still use SequelTools? If not could you provide support for this situation? Thank you.

Best,
Justin

**Comment by aseetharam** [comment]
Hi Justin,

Thanks for trying out SequelTools! Yes, you can run QC on only subreads files as well. Please check the README file, specifically the [QC](https://github.com/ISUgenomics/SequelTools#the-qc-tool) section, where we provided examples of running SequelTools with and without scraps. Hope this helps!

**Comment by justincbagley** [comment]
Sorry, I didn't see that. I've been in kind of a hurry today. Couple more related points... In the README, 

1. Subread BAM files are passed to file 'subreads.txt' but then this is never used in any of the examples. Instead, a file named 'subFiles.txt' is referred to in the examples. 
2. Likewise, scrap BAM files are passed to file 'scraps.txt' but then this is never used again. Instead, a file named 'scrFiles.txt' is referred to in the examples. 
3. Also, there is no example for running the Read Filtering tool without scraps, and this is the tool I'm most interested in. Can this tool also be run without scraps (without the -c flag)?

I have proposed a minor change fixing 1 and 2 above, so please accept that or clarify. 

What about 3? I would test this but I don't have SequelTools installed yet, and I want to know whether it is worth the trouble. Thanks for your help.

Best,
Justin

**Comment by aseetharam** [comment]
Hi Justin!

Nice catch! Yes, those 2 files are the same (file of file names, scraps, and subreads, as the name suggests). Yes, you can run the filtering tool just with the subreads file.
Thanks for your feedback, we will fix the README soon!

Best regards,
