### ISSUE TITLE
FILES_FOR_R

### ISSUE THREAD

**Issue by s4251484** [ISUgenomics/SequelTools#2]
Hi

thanks for developing this tool!
i encouter an error as such:
line 710: $((${#FILES_FOR_R} - 1)): substring expression < 0

when i run 
SequelTools.sh -t Q -u /Users/s4251484/Desktop/sequeltool.txt

Please enlighten!

**Comment by aseetharam** [comment]
Thanks for trying SequelTools! It looks like the shell you are using doesn't support Command Substitutions. Can you let us know what environment you're using for running SequelTools?

**Comment by s4251484** [comment]
HI!

Thanks for your prompt reply! I’m running it on local mac terminal env with R Samtools and Python and even the bash files in SequelTools/Script folder in the path.

Best regards
Chian Teng

HDR Candidate | PhD
Queensland Alliance for Agriculture and Food Innovation (QAAFI)
Queensland Bioscience Precinct [Building# 80]
The University of Queensland, St Lucia 4072 Australia
Mobile: 0411322852
Email: chian.ong1@uqconnect.edu.au/<mailto:chian.ong1@uqconnect.edu.au/> uqcong7@uq.edu.au<mailto:uqcong7@uq.edu.au>
Website: www.qaafi.uq.edu.au<http://www.qaafi.uq.edu.au/>

Delivery address
University of Queensland
QAAFI - QBP/IMB Loading Dock
Chian Ong
Lvl 1, IMB Bld 80
Services Road
THE UNIVERSITY OF QUEENSLAND QLD

**Comment by aseetharam** [comment]
Hi Chian,

Can you try running this in a native Linux environment (non-Mac)? Quick look upon that error tells me that Mac doesn't support something required for SequelTools.
https://superuser.com/q/1033273

Thank you for reporting this, we will try to fix this by converting the expression to something generic in the next version.

Thanks,

**Comment by s4251484** [comment]
Hi Dr Seetharam

Wow! I think you detected the problem. Here are the run results on two of my systems:

PBS cluster (linus) – no R installed

s4251484@fl102:/30days/s4251484/bwa_bcf> STR="Hello World"
s4251484@fl102:/30days/s4251484/bwa_bcf> echo ${STR:6:-1}
Worl
s4251484@fl102:/30days/s4251484/bwa_bcf> echo ${STR:6:$((${#STR} - 6 - 1))}
Worl

Local Mac Unix
d-i89-241-70:~ s4251484$ STR="Hello World"
d-i89-241-70:~ s4251484$ echo ${STR:6:-1}
-bash: -1: substring expression < 0
d-i89-241-70:~ s4251484$ echo ${STR:6:$((${#STR} - 6 - 1))}
Worl


Best regards
Chian Teng

HDR Candidate | PhD
Queensland Alliance for Agriculture and Food Innovation (QAAFI)
Queensland Bioscience Precinct [Building# 80]
The University of Queensland, St Lucia 4072 Australia
Mobile: 0411322852
Email: chian.ong1@uqconnect.edu.au/<mailto:chian.ong1@uqconnect.edu.au/> uqcong7@uq.edu.au<mailto:uqcong7@uq.edu.au>
Website: www.qaafi.uq.edu.au<http://www.qaafi.uq.edu.au/>

Delivery address
University of Queensland
QAAFI - QBP/IMB Loading Dock
Chian Ong
Lvl 1, IMB Bld 80
Services Road
THE UNIVERSITY OF QUEENSLAND QLD
