### ISSUE TITLE
quality control 'the BAM file  is empty or does not exist'

### ISSUE THREAD

**Issue by droeatumn** [ISUgenomics/SequelTools#6]
[Kir5_P1_8_999F_all.contigs_KP420442_sorted.bam.gz](https://github.com/ISUgenomics/SequelTools/files/4430459/Kir5_P1_8_999F_all.contigs_KP420442_sorted.bam.gz)
[subreads.txt](https://github.com/ISUgenomics/SequelTools/files/4430460/subreads.txt)
I am running today's version on OSX 10.15.4 with the attached files (I gzipped the bam for the sake of uploading). This is what happened:

```
~/git/SequelTools/Scripts/SequelTools.sh -t Q -u subFiles.txt 
Beginning quality control function

Running in NO_SCRAPS mode
the BAM file  is empty or does not exist

```

**Comment by DavidEHufnagel** [comment]
Hello Dave,

Thanks for trying out our program!  The issue seems to be that you set the
file of BAM input files to "subFiles.txt" rather than to your file,
"subreads.txt".  Give that a shot and let me know if it doesn't work out!

Best, David E. Hufnagel

**Comment by droeatumn** [comment]
You are correct. Thank you!

**Comment by DavidEHufnagel** [comment]
no worries!
